Repository bounswe/bounswe2019group11, pull requests merged in 2019-11, with the labels that each got.

#196 implement comments endpoint for articles
  backend/helpers/database.js
  backend/helpers/errors.js
  backend/models/article.js
  backend/models/articleComment.js
  backend/routes/article.js
  backend/services/article.js
  backend/swagger.json
Labels: Component: Backend, Type: Documentation, Type: Enhancement

#202 add missing authentication check on edit comment
  backend/routes/article.js
  backend/services/article.js
  backend/swagger.json
Labels: Component: Backend, Type: Bug

#200 add missing match stage to the get comments pipeline
  backend/services/article.js
Labels: Component: Backend, Type: Bug

#203 add up vote, down vote, clear vote endpoints
  backend/helpers/errors.js
  backend/models/article.js
  backend/models/articleVote.js
  backend/routes/article.js
  backend/services/article.js
  backend/swagger.json
Labels: Component: Backend, Type: Documentation, Type: Enhancement

#206 Article comments are added to mobile.
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/ListViewAdapter.java
  android/app/src/main/java/com/papel/data/Article.java
  android/app/src/main/java/com/papel/data/Comment.java
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/activity_read_article.xml
  android/app/src/main/res/layout/article_header.xml
  android/app/src/main/res/layout/custom_list_row.xml
  android/app/src/main/res/layout/edit_comment_prompt.xml
  android/app/src/main/res/menu/article_comments_menu.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Priority: High, Ready for Review

#211 Add Firebase to project and receive notifications
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/papel/FirebaseNotificationService.java
  android/app/src/main/java/com/papel/ui/login/LoginActivity.java
  android/build.gradle
Labels: Component: Mobile, Ready for Review

#218 implement sign-up/login with google
  backend/.env
  backend/helpers/errors.js
  backend/models/user.js
  backend/package.json
  backend/routes/auth.js
  backend/services/auth.js
  backend/swagger.json
Labels: Component: Backend, Type: Documentation, Type: Enhancement

#219 Add search android
  android/app/build.gradle
  android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java
  android/build.gradle
Labels: Component: Mobile, Status: Available, Type: Enhancement

#220 Google login and signup
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/data/GoogleUserAccount.java
  android/app/src/main/java/com/papel/ui/login/GoogleSignUpActivity.java
  android/app/src/main/java/com/papel/ui/login/LoginActivity.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/activity_google_sign_up.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Priority: High, Type: Enhancement

#222 Changed the list row design and changed the date format of Articles
  android/app/src/main/java/com/papel/ListViewAdapter.java
  android/app/src/main/java/com/papel/data/Article.java
  android/app/src/main/res/layout/custom_list_row.xml
Labels: Component: Mobile, Priority: Medium, Ready for Review, Type: Bug

#225 Implemented trading equipments page.
  android/app/src/main/java/com/papel/MainActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentListViewAdapter.java
  android/app/src/main/java/com/papel/ui/tools/ToolsFragment.java
  android/app/src/main/java/com/papel/ui/tools/ToolsViewModel.java
  android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsFragment.java
  android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsViewModel.java
  android/app/src/main/res/drawable/ic_menu_trading.xml
  android/app/src/main/res/layout/fragment_tools.xml
  android/app/src/main/res/layout/fragment_trading_equipments.xml
  android/app/src/main/res/menu/activity_main_drawer.xml
  android/app/src/main/res/navigation/mobile_navigation.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Priority: High, Priority: Medium, Ready for Review, Type: Enhancement

#226 Implemented article voting in mobile
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/data/Article.java
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/drawable/ic_dislike.xml
  android/app/src/main/res/drawable/ic_like.xml
  android/app/src/main/res/layout/article_header.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Estimation: M, Priority: Medium, Ready for Review, Type: Enhancement

#233 Added Authorized Request, Stock Searchbar for Add Stock, Location Geocoding for Profiles
  frontend/papel-frontend/src/Article/Article.js
  frontend/papel-frontend/src/Profile/Portfolio.js
  frontend/papel-frontend/src/Profile/Profile.js
  frontend/papel-frontend/src/Profile/ProfileCard.js
  frontend/papel-frontend/src/helpers/geocoder.js
  frontend/papel-frontend/src/helpers/request.js
Labels: Component: Frontend

#230 return user vote on article endpoints
  backend/helpers/auth.js
  backend/middlewares/isAuthenticated.js
  backend/routes/article.js
  backend/services/article.js
  backend/swagger.json
Labels: Component: Backend, Type: Enhancement

#238 Add selecting Google account in login
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/ui/login/LoginActivity.java
Labels: Component: Mobile, Ready for Review

#245 Added user vote to article page
  android/app/src/main/java/com/papel/data/Article.java
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/article_header.xml
Labels: Component: Mobile, Ready for Review

#242 Implement endpoints and cron jobs for currencies
  backend/.env
  backend/app.js
  backend/helpers/errors.js
  backend/jobs/jobs.js
  backend/models/currency.js
  backend/package.json
  backend/routes/currency.js
  backend/scripts/databaseInitializers.js
  backend/services/currency.js
  backend/swagger.json
Labels: Component: Backend, Type: Documentation, Type: Enhancement

#241 Android profile
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/MainActivity.java
  android/app/src/main/java/com/papel/data/Article.java
  android/app/src/main/java/com/papel/data/Comment.java
  android/app/src/main/java/com/papel/ui/articles/ArticlesFragment.java
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java
  android/app/src/main/java/com/papel/ui/profile/ProfileListViewAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/activity_profile.xml
  android/app/src/main/res/layout/fragment_profile_subpage.xml
  android/app/src/main/res/layout/portfolio_row.xml
  android/app/src/main/res/layout/profile_row.xml
Labels: Component: Mobile

#247 Changed trading equipment detail page design
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java
  android/app/src/main/res/layout/activity_trading_equipment_detail.xml
  android/app/src/main/res/layout/trading_equipment_header.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Estimation: S, Priority: High, Ready for Review, Status: In Progress, Type: Enhancement

#250 Profile articles & portfolios implementation
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/profile/ProfileListViewAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java
  android/app/src/main/res/layout/profile_row.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Ready for Review, Status: Completed, Type: Enhancement

#252 Fix the bug where user sees the portfolio add button in others' portfolios.
  android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/PortfolioFragment.java
  android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java
Labels: Component: Mobile, Priority: Medium, Type: Enhancement

#254 Profile Pages for Other Users Added and Small Changes&Fixes
  frontend/papel-frontend/src/App.js
  frontend/papel-frontend/src/Article/Article.js
  frontend/papel-frontend/src/Article/ArticlePreview.js
  frontend/papel-frontend/src/Profile/Portfolio.js
  frontend/papel-frontend/src/Profile/Profile.js
  frontend/papel-frontend/src/Profile/ProfileCard.js
  frontend/papel-frontend/src/Profile/UserProfile.css
  frontend/papel-frontend/src/Profile/UserProfile.js
  frontend/papel-frontend/src/Trading/TradingEquipment.js
  frontend/papel-frontend/src/helpers/request.js
Labels: Component: Frontend, Estimation: S, Priority: Medium

#236 Home Page Update - Articles/Events and Currency Preview Section
  frontend/papel-frontend/src/App.css
  frontend/papel-frontend/src/App.js
  frontend/papel-frontend/src/Article/Article.css
  frontend/papel-frontend/src/Article/Article.js
  frontend/papel-frontend/src/Article/Articles.js
  frontend/papel-frontend/src/Article/CommentPreview.js
  frontend/papel-frontend/src/Home/ArticleListPreview.js
  frontend/papel-frontend/src/Home/CurencyChart.js
  frontend/papel-frontend/src/Home/Home.css
  frontend/papel-frontend/src/Home/Home.js
  frontend/papel-frontend/src/Home/USD.js
  frontend/papel-frontend/src/Login/Login.js
  frontend/papel-frontend/src/Trading/TradingEquipment.js
Labels: Component: Frontend, Status: In Progress

#264 Check user and author id matches when an article comment is pressed
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsFragment.java
Labels: Component: Mobile, Ready for Review

#249 fix cron job scripts
  backend/jobs/jobs.js
  backend/package.json
Labels: Component: Backend, Type: Bug

#257 Investments backend
  backend/app.js
  backend/helpers/errors.js
  backend/models/investments.js
  backend/routes/investments.js
  backend/routes/profile.js
  backend/services/investments.js
Labels: Component: Backend, Ready for Review

#271 revert comments on currency
  backend/routes/currency.js
  backend/services/currency.js
Labels: Component: Backend, Type: Bug

#266 Add currency
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/data/Currency.java
  android/app/src/main/java/com/papel/data/Stock.java
  android/app/src/main/java/com/papel/data/TradingEquipment.java
  android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentListViewAdapter.java
  android/app/src/main/java/com/papel/ui/tradingequipments/TradingEquipmentsFragment.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/activity_trading_equipment_detail.xml
Labels: Component: Mobile, Type: Enhancement

#273 Implement predictions for currencies
  backend/helpers/errors.js
  backend/helpers/prediction.js
  backend/jobs/jobs.js
  backend/models/currencyComment.js
  backend/models/prediction.js
  backend/models/user.js
  backend/routes/currency.js
  backend/services/currency.js
  backend/swagger.json
Labels: Component: Backend, Type: Documentation, Type: Enhancement

#253 Added trading equipments and currencies to the portfolio
  backend/models/portfolio.js
  backend/routes/portfolio.js
  backend/services/portfolio.js
Labels: Ready for Review

#274 Added comments to trading equipments
  android/app/src/main/java/com/papel/data/Comment.java
  android/app/src/main/java/com/papel/data/Currency.java
  android/app/src/main/java/com/papel/data/Stock.java
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentListViewAdapter.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/trading_equipment_header.xml
  android/app/src/main/res/layout/trading_equipment_row.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Ready for Review

#275 return id on currencies
  backend/services/currency.js
  backend/swagger.json
Labels: Component: Backend, Type: Enhancement

#277 Prediction for trading equipment is implemented.
  android/app/src/main/java/com/papel/data/Currency.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/layout/trading_equipment_header.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Priority: High, Ready for Review

#280 Profile update android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/papel/Constants.java
  android/app/src/main/java/com/papel/data/User.java
  android/app/src/main/java/com/papel/ui/profile/FollowAdapter.java
  android/app/src/main/java/com/papel/ui/profile/PendingFollowAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSettingsActivity.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileSubpageFragment.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
  android/app/src/main/res/drawable/accept_button.xml
  android/app/src/main/res/drawable/decline_button.xml
  android/app/src/main/res/layout/activity_profile.xml
  android/app/src/main/res/layout/activity_profile_settings.xml
  android/app/src/main/res/layout/follow_pending_row.xml
  android/app/src/main/res/layout/follow_row.xml
  android/app/src/main/res/menu/menu_profile.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile

#278 documentation for currency addition to portfolio
  backend/swagger.json
Labels: Ready for Review

#284 Hot fix
  android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java
  android/app/src/main/java/com/papel/ui/profile/PendingFollowAdapter.java
  android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java
Labels: Component: Mobile, Estimation: XS, Priority: Critical, Type: Bug

#282 "No comment" text added
  android/app/src/main/java/com/papel/ui/articles/ReadArticleActivity.java
  android/app/src/main/java/com/papel/ui/portfolio/TradingEquipmentDetailActivity.java
  android/app/src/main/res/layout/article_header.xml
  android/app/src/main/res/layout/trading_equipment_header.xml
  android/app/src/main/res/values/strings.xml
Labels: Component: Mobile, Priority: Medium, Ready for Review

#285 Add currency to portfolio
  android/app/src/main/java/com/papel/data/Currency.java
  android/app/src/main/java/com/papel/ui/portfolio/PortfolioDetailActivity.java
  android/app/src/main/java/com/papel/ui/utils/ResponseParser.java
Labels: Component: Backend, Component: Frontend, Estimation: S, Priority: Critical, Status: Completed, Type: Enhancement

#287 documentation for /investments and /investments/:id
  backend/swagger.json
Labels: Status: In Progress

#288 Profile follow button fix
  android/app/src/main/java/com/papel/ui/profile/ProfileActivity.java
  android/app/src/main/res/layout/activity_profile.xml
Labels: Component: Mobile, Priority: Critical, Ready for Review, Type: Enhancement

#276 Changes on Articles, Article, Home pages
  frontend/papel-frontend/src/App.js
  frontend/papel-frontend/src/Article/AddArticle.js
  frontend/papel-frontend/src/Article/Article.js
  frontend/papel-frontend/src/Article/Articles.js
  frontend/papel-frontend/src/Article/CommentPreview.js
  frontend/papel-frontend/src/Currency/CurencyCh.js
  frontend/papel-frontend/src/Currency/Currencies.js
  frontend/papel-frontend/src/Currency/CurrencyTable.js
  frontend/papel-frontend/src/Currency/CurrencyView.js
  frontend/papel-frontend/src/EconEvent/EconEvent.js
  frontend/papel-frontend/src/EconEvent/EconEventPreview.js
  frontend/papel-frontend/src/EconEvent/EconEvents.js
  frontend/papel-frontend/src/Home/EventListPreview.js
  frontend/papel-frontend/src/Home/Home.css
  frontend/papel-frontend/src/Home/Home.js
Labels: Component: Frontend, Status: Completed
